dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views
	
urlpatterns = [
	path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dogs/', views.dogs_index, name='index'),
    path('dogs/<int:dog_id>/', views.dogs_detail, name='detail'),
    path('dogs/create', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/update', views.DogUpdate.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/delete', views.DogDelete.as_view(), name='dogs_delete'),
    path('dogs/<int:dog_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('traits/', views.TraitList.as_view(), name='traits_index'),
    path('traits/<int:pk>/', views.TraitDetail.as_view(), name='traits_detail'),
    path('traits/create/', views.TraitCreate.as_view(), name='traits_create'),
    path('traits/<int:pk>/update/', views.TraitUpdate.as_view(), name='traits_update'),
    path('traits/<int:pk>/delete/', views.TraitDelete.as_view(), name='traits_delete'),
    path('dogs/<int:dog_id>/assoc_trait/<int:trait_id>/', views.assoc_trait, name='assoc_trait'),
    path('dogs/<int:dog_id>/remove_trait/<int:trait_id>/', views.remove_trait, name='remove_trait'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

MEALS = (
    ('B', 'Breakfast'),
    ('D', 'Dinner'),
    ('S', 'Snack')
)

class Trait(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('traits_detail', kwargs={'pk': self.id})

# Create your models here.
class Dog(models.Model):
    name = models.CharField(max_length=50)
    breed =  models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    age = models.IntegerField()
    traits = models.ManyToManyField(Trait)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'dog_id': self.id})
    
class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        # default to a snack
        default=MEALS[2][0]
        )
    # Create a dog_id foreign key
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Dog, Trait
from .forms import FeedingForm

def home(request):
    return render(request, 'home.html')

def about(request):
    dogs = Dog.objects.all()
    return render(request, 'about.html', {
        'dogs': dogs
    })

def dogs_index(request):
    dogs = Dog.objects.all()
    return render(request, 'dogs/index.html', {
        'dogs': dogs
    })

def dogs_detail(request, dog_id):
    dog = Dog.objects.get(id=dog_id)
    # list of all traits dog currently has
    id_list = dog.traits.all().values_list('id')
    traits_not_had = Trait.objects.exclude(id__in=id_list)
    feeding_form = FeedingForm()
    return render(request, 'dogs/detail.html', {
        'dog': dog, 'feeding_form': feeding_form,
         'traits': traits_not_had })

def add_feeding(request, dog_id):
      # create a ModelForm instance using the data in request.POST
    form = FeedingForm(request.POST)
    # validate the form
    if form.is_valid():
    # don't save the form to the db until it
    # has the dog_id assigned
        new_feeding = form.save(commit=False)
        new_feeding.dog_id = dog_id
        new_feeding.save()
    return redirect('detail', dog_id=dog_id)

def assoc_trait(request, dog_id, trait_id):
    Dog.objects.get(id=dog_id).traits.add(trait_id)
    return redirect('detail', dog_id=dog_id)

def remove_trait(request, dog_id, trait_id):
    Dog.objects.get(id=dog_id).traits.remove(trait_id)
    return redirect('detail', dog_id=dog_id)

class DogCreate(CreateView):
    model = Dog
    fields = ['name', 'breed', 'description', 'age']

class DogUpdate(UpdateView):
    model = Dog
    fields = ['breed', 'description', 'age']

class DogDelete(DeleteView):
    model = Dog
    success_url = '/dogs'

class TraitList(ListView):
    model = Trait

class TraitDetail(DetailView):
    model = Trait

class TraitCreate(CreateView):
    model = Trait
    fields = ['name', 'description']

class TraitUpdate(UpdateView):
    model = Trait
    fields = ['name', 'description']

class TraitDelete(DeleteView):
    model = Trait
    success_url = '/traits'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Dog Collector</h1>
<hr>
<p>We try to log as many dogs as we can at Dog Collector</p>
<br>
{% if dogs %}
    <p>Currently we log your dogs 
        {% for key in dogs.0.keys %}
            {{ key }}, 
        {% endfor %}
    </p>
{% else %}
    <p>No dogs yet, hold on.</p>
{% endif %}


{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Dog Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Dog Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'traits_create' %}">Add a Trait</a></li>
          <li><a href="{% url 'traits_index' %}">View All Traits</a></li>
          <li><a href="{% url 'dogs_create' %}">Add a Dog</a></li>
          <li><a href="{% url 'index' %}">Check Out All the Dogs</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2024 Dog Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/dogs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ dog.name }}</span>
        <p>Breed: {{ dog.breed }}</p>
        <p>Description: {{ dog.description|linebreaks }}</p>
        {% if dog.age > 0 %}
          <p>Age: {{ dog.age }}</p>
        {% else %}
          <p>Age: Puppy</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'dogs_update' dog.id %}">Edit</a>
        <a href="{% url 'dogs_delete' dog.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' dog.id %}" method="POST">
      {% csrf_token %}
      {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in dog.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ dog.name }}'s Current Traits</h3>
    {% if dog.traits.count %}
      {% for trait in dog.traits.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span>{{ trait.name }}</span><h6>{{ trait.description }}</h6>
            </span>
            <div class="card-action">
              <form action="{% url 'remove_trait' dog.id trait.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">Remove<i class="material-icons right">delete</i></button>
              </form>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Traits Yet, Add Some!</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Traits for {{ dog.name }}</h3>
    {% if traits.count %}
      {% for trait in traits.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span>{{ trait.name }}</span> <h6>{{ trait.description }}</h6>
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_trait' dog.id trait.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{dog.name}} Already Has All Traits Available</h5>
    {% endif %}
  </div>
</div>
<script>
  const dateEl = document.getElementById('id_date');
  // M is Materialize's global variable
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Dog List</h1>

{% for dog in dogs %}
  <div class="card">
    <a href="{% url 'detail' dog.id %}">
      <div class="card-content">
        <span class="card-title">{{ dog.name }}</span>
        <p>Breed: {{ dog.breed }}</p>
        <p>Description: {{ dog.description| linebreaks}}</p>
        {% if dog.age > 0 %}
          <p>Age: {{ dog.age }}</p>
        {% else %}
          <p>Age: Puppy</p>
        {% endif %}
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1 class="first-message">The Dog Collector</h1>
<hr>



{% endblock %}

main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Dog</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' dog.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/dog_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
        <h1>Edit <span class='teal-text'>{{object.name}}</span></h1>
    {% else %}
        <h1>Add Dog</h1>
    {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form class= "add_dog" action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/trait_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Trait</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'traits_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/trait_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Trait Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ trait.name }}</span>
        <p>Description: {{ trait.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'traits_update' trait.id %}">Edit</a>
        <a href="{% url 'traits_delete' trait.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/trait_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Trait</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/trait_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Trait List</h1>

{% for trait in trait_list %}
  <a href="{% url 'traits_detail' trait.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ trait.name }}</span>
            <p>Description: {{ trait.description }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}